---
fail_fast: true
repos:
  # Generic repos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0  # Use the ref you want to point at
    hooks:
      # This prevents issues if not managing git-lfs
      - id: check-added-large-files
      # This prevents problems for multi OS
      - id: check-case-conflict
      # This prevents having executables that cannot be executed
      - id: check-executables-have-shebangs
      # Check JSON, XML and YAML
      - id: check-json
      # Prevents commiting unmergeable files
      - id: check-merge-conflict
      # Removes spaces at end of lines
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # AWS Creds
      - id: detect-aws-credentials
      # Prevents commiting to master
      # - id: no-commit-to-branch

  # Change tabs for spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, "2"]

  # For deploy and validation scripts
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: markdownlint
        args: [--rules, "~MD013"]
      - id: shellcheck
        args: [-e, "SC2124"]

  # Advanced YAML Linter that works on .template files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.19.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml|template)$
        args: [--config-data, "{extends: default, rules: {line-length: {max: 240, level: warning}}, yaml-files: ['*.yaml', '*.yml', '*.yamllint', '*.template']}"]

