on:
    pull_request:
        tags:
            - 'v*'
    push:
        tags:
            - 'v*'
jobs:
    buildAndPushDocker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: olegtarasov/get-tag@v2
              id: tagName
            - name: Login to the docker registry of github packages
              run: echo "Building package of version" $GIT_TAG_NAME
            - name: Building the docker action 
              run: docker build . --file Dockerfile --tag hola-gente-action:$GIT_TAG_NAME
            - name: Taging the docker and pushing to repo  
              run: |
                echo ${{ secrets.LOGIN_TOKEN }} || docker login -u franusierra --password-stdin docker.pkg.github.com
                docker tag hola-gente-action:$GIT_TAG_NAME docker.pkg.github.com/franusierra/action-sample-sngular/hola-gente-action:$GIT_TAG_NAME
                docker push docker.pkg.github.com/franusierra/action-sample-sngular/hola-gente-action:$GIT_TAG_NAME
              